# -*- mode: python -*-
Import("env")

env = env.Clone()

env.CppUnitTest(
    target="virtual_collection_test",
    source=[
        "external_record_store_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/catalog/collection_options",
        "$BUILD_DIR/mongo/db/query/virtual_collection/virtual_collection",
        "$BUILD_DIR/mongo/db/storage/record_store_base",
    ],
)

env.CppUnitTest(
    target="csv_file_test",
    source=[
        "csv_file_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query/virtual_collection/csv_file",
        "$BUILD_DIR/mongo/db/server_base",
    ],
)
