# -*- mode: python -*-
Import("env")

env = env.Clone()

env.CppUnitTest(
    target="virtual_collection_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="csv_file_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="csv_bm",
    source=[
        "csv_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query/virtual_collection/csv_file",
    ],
)
