# -*- mode: python -*-
Import("env")

env = env.Clone()

env.CppUnitTest(
    target="virtual_collection_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="csv_file_test",
    source=[],
    LIBDEPS=[],
)
